environment  = "Production"
rg_location  = "East US"
la_rg_name   = "leonid-abasov"
la_arc_name  = "leonidabasov"
bss_rg_name  = "be-sport-smart"
bss_vn_name  = "be-sport-smart"
bss_k8s_name = "be-sport-smart"
bss_kv_name  = "be-sport-smart"